version: "3.3"

services:     
  backend:
    container_name: sourcesage-challenge-api
    build: backend
    command: python3 run.py
    volumes:
      - ./backend:/code
    ports:
      - "5000:5000"
  
  frontend:
    container_name: sourcesage-challenge-frontend
    build: frontend
    command: ./entrypoint.sh
    volumes:
      - ./frontend:/code
    ports:
      - "4200:4200"